EN = [
    "I am looking for a 1.5-room apartment in Zurich near ETH, ideally under CHF 2200.",
    "I want to live close to my workplace, max 20 minutes by public transport.",
    "Looking for something in Zurich that feels quiet and bright.",
    "We are looking for an apartment for 3 people with at least 2 bedrooms.",
    "I would like something near a lake, preferably quiet.",
    "Looking for an apartment in Winterthur, from 70 m², ideally with a balcony.",
    "I want something that feels modern, but not sterile or uncomfortable.",
    "I am looking for an apartment in Oerlikon with an elevator and a washing machine in the unit.",
    "What matters most to me is that the area feels safe and pleasant to live in.",
    "I am looking for something small in Zurich, ideally furnished.",
    "I am looking for a 2.5 to 3-room apartment in Zurich or directly adjacent, ideally with a max 25-minute commute to Zurich HB, at least 65 m², a balcony or loggia, and if possible not on the ground floor.",
    "We are a family with one child and are looking in Zug or Baar for an apartment with 3.5 or 4 rooms, at least 85 m², budget up to CHF 3600, ideally in an area with good schools, little traffic, and some greenery nearby.",
    "I am looking for something in Lausanne near EPFL or with a good metro connection there, ideally 1 to 2 rooms, furnished, and overall more practical than fancy.",
    "We would like to live in Basel, ideally with 2 bedrooms, good tram connections, a washer-dryer tower, and it would be great if shopping were easily reachable on foot.",
    "I am looking for an apartment that simply feels pleasant: lots of light, a quiet street, not too anonymous, more like a neighborhood where you would enjoy staying long term.",
    "Looking for something in Zurich Districts 3, 4, or 5, under CHF 3200, with at least 2.5 rooms and ideally a modern kitchen.",
    "Above all, I want to avoid a long commute; everything else is relatively open.",
    "We are looking for something family-friendly, where living with children works well.",
    "I would like an apartment with a good layout, large windows, and if possible a balcony.",
    "Looking for an apartment in Winterthur, not too far from the train station, but please not directly on a major road.",
    "I am looking for a 4-room apartment in Zurich North, ideally from 95 m², with an elevator; 2 bathrooms would be a plus, rent up to CHF 4200, and the trip to Kantonsschule Rämibühl should be doable by public transport in around 30 minutes.",
    "We are looking for an apartment for 2 adults and 1 child in the Thalwil, Horgen, or Wädenswil area, ideally near the lake, with at least 3.5 rooms, from 90 m², budget up to CHF 3800, a balcony or small garden, and in an environment that feels quiet, safe, and not too densely built.",
    "I am looking for something more affordable in Basel. It does not need to be large, but the location should be practical.",
    "The most important thing to me is that the apartment is quiet and not dark.",
    "I am looking for an apartment in Bern, ideally with max 15 minutes to the train station, 2 to 3 rooms, and no more than CHF 2500.",
]

DE = [
    "Ich suche eine 1.5 Zimmer Wohnung in Zürich in der Nähe der ETH, am besten unter 2200 CHF.",
    "Ich möchte nah an meiner Arbeit wohnen, max 20 Minuten mit dem ÖV.",
    "Suche was in Zürich, das sich ruhig und hell anfühlt.",
    "Wir suchen eine Wohnung für 3 Personen mit mindestens 2 Schlafzimmern.",
    "Ich hätte gern etwas in Seenähe, gern eher ruhig.",
    "Suche Wohnung in Winterthur, ab 70 m², gern mit Balkon.",
    "Ich möchte etwas, das modern, aber nicht ungemütlich ist.",
    "Ich suche eine Wohnung in Oerlikon mit Lift und Waschmaschine in der Wohnung.",
    "Mir ist vor allem wichtig, dass die Gegend sicher ist und sich gut zum Wohnen anfühlt.",
    "Ich suche was Kleines in Zürich, gern möbliert.",
    "Ich suche eine 2.5 bis 3 Zimmer Wohnung in Zürich oder direkt angrenzend, idealerweise mit max 25 Minuten Pendelzeit zum HB, mindestens 65 m², Balkon oder Loggia, und wenn möglich nicht im Erdgeschoss.",
    "Wir sind eine Familie mit einem Kind und suchen in Zug oder Baar eine Wohnung mit 3.5 oder 4 Zimmern, mindestens 85 m², Budget bis 3600 CHF, gern in einer Gegend mit guten Schulen, wenig Verkehr und etwas Grün in der Nähe.",
    "Ich suche etwas in Lausanne in der Nähe von EPFL oder mit guter Metro-Anbindung dorthin, am besten 1 bis 2 Zimmer, möbliert, und insgesamt eher praktisch als fancy.",
    "Wir möchten in Basel wohnen, am liebsten mit 2 Schlafzimmern, guter Tram-Anbindung, Waschturm, und es wäre super, wenn Einkaufen zu Fuß gut möglich ist.",
    "Ich suche eine Wohnung, die sich einfach angenehm anfühlt — viel Licht, ruhige Straße, nicht zu anonym, eher ein Quartier, in dem man gern länger bleibt.",
    "Suche was in Zürich Kreis 3, 4 oder 5, unter 3200 CHF, mit mindestens 2.5 Zimmern und möglichst moderner Küche.",
    "Ich will vor allem keinen langen Arbeitsweg, der Rest ist relativ offen.",
    "Wir suchen etwas familienfreundliches, wo man mit Kindern gut leben kann.",
    "Ich hätte gern eine Wohnung mit gutem Schnitt, großen Fenstern und wenn möglich Balkon.",
    "Suche Wohnung in Winterthur, nicht zu weit vom Bahnhof, aber bitte nicht direkt an einer großen Straße.",
    "Ich suche eine 4 Zimmer Wohnung in Zürich Nord, idealerweise ab 95 m², Lift, 2 Badezimmer wären ein Plus, Miete bis 4200 CHF, und die Fahrt zur Kantonsschule Rämibühl sollte mit dem ÖV in ungefähr 30 Minuten machbar sein.",
    "Wir suchen eine Wohnung für 2 Erwachsene und 1 Kind im Raum Thalwil, Horgen oder Wädenswil, gern nahe am See, mit mindestens 3.5 Zimmern, ab 90 m², Budget bis 3800 CHF, Balkon oder kleiner Garten, und in einer Umgebung, die sich ruhig, sicher und nicht zu dicht bebaut anfühlt.",
    "Ich suche was Günstigeres in Basel, muss nicht groß sein, aber die Lage sollte praktisch sein.",
    "Am wichtigsten ist mir, dass die Wohnung ruhig ist und nicht dunkel.",
    "Ich suche eine Wohnung in Bern, am besten mit max 15 Minuten zum Bahnhof, 2 bis 3 Zimmern und nicht mehr als 2500 CHF.",
]

MIXED = [
    "Ich suche eine Wohnung im Raum Zürich, Dübendorf oder Wallisellen, idealerweise 2.5 bis 3.5 Zimmer, ab 70 m², Budget bis 3100 CHF, max 25 Minuten mit dem ÖV bis Stadelhofen, gern mit Balkon, Waschmaschine in der Wohnung oder eigenem Waschturm, und wenn möglich in einer Gegend, die sich ruhig und nicht zu urban hektisch anfühlt.",
    "Wir suchen als Familie zu dritt etwas im Raum Kilchberg, Rüschlikon oder Thalwil, am liebsten nahe am See oder mit schneller Verbindung nach Zürich, mindestens 3.5 Zimmer, ab 90 m², Budget bis 4300 CHF, gern mit Balkon / Terrasse, Lift, Keller, und wichtig wären uns gute Schulen, Parks oder Spielplätze in der Nähe sowie eine Umgebung, in der man sich auch abends sicher fühlt.",
    "I'm looking for an apartment in the greater Zurich area, ideally somewhere like Oerlikon, Altstetten, or Schlieren, with at least 60 sqm, preferably 2 to 3 rooms, a commute under 30 minutes to Zurich HB door to door, and it would be great if the place had a balcony, good light, and access to shops and public transport within walking distance.",
    "We are a family of 3 looking around Basel for something with 2 or 3 bedrooms, ideally 85 sqm or more, budget up to CHF 3500, in an area with good schools, quiet streets, and enough nearby amenities that daily life is easy without needing a car all the time.",
    "Ich suche etwas Kleineres in Lausanne, möglichst in der Nähe von EPFL, gern möbliert, unter 2100 CHF, mit guter Anbindung, und am besten in einer Ecke, die sich sicher, entspannt und nicht komplett anonym anfühlt.",
    "I'm looking for a place near Geneva city center but not right in the busiest part, ideally with 2 bedrooms, budget up to CHF 3600, good transport access, and a neighborhood that feels clean, safe, and a bit more residential than hectic.",
]

ALL = EN + DE + MIXED
GROUPS = [("EN", EN), ("DE", DE), ("MIXED", MIXED)]
